language: python
python:
  - 2.7
  - 3.4
jdk:
  - oraclejdk8
sudo: required
dist: trusty

before_install:
  - jdk_switcher use oraclejdk8

install:
  - pip install numpy matplotlib

script: ./gradlew test --info
